apiVersion: v1
kind: ConfigMap
metadata:
  name: order-intake-api-config
data:
  SPRING_PROFILES_ACTIVE: "gcp"
  PUBSUB_PROJECT: "${PROJECT_ID}"
  CLOUD_SQL_INSTANCE: "${PROJECT_ID}:us-central1:tb-otd-pg"
